# Generated by Django 3.1.4 on 2020-12-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201230_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='updated_at',
            new_name='deposited_at',
        ),
        migrations.RenameField(
            model_name='usertransaction',
            old_name='updated_by',
            new_name='deposited_by',
        ),
    ]
