# Generated by Django 3.1.4 on 2020-12-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201230_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='statis_transaction',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
