# Generated by Django 3.1.4 on 2020-12-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201230_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertransaction',
            old_name='statis_transaction',
            new_name='status_transaction',
        ),
    ]
