# Generated by Django 3.1.4 on 2020-12-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201230_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='deposited_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
