# Generated by Django 3.1.4 on 2020-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201230_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransaction',
            name='type_transaction',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
